# Generated by Django 5.0.6 on 2024-07-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_icon'),
        ('food_types', '0002_auto_20240610_0443'),
        ('foods', '0007_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_types.foodtype', verbose_name='Тип'),
        ),
    ]
