# Generated by Django 3.2.9 on 2024-06-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20240610_0443'),
        ('statuses', '0002_auto_20240610_0443'),
        ('users', '0007_auto_20240610_0443'),
        ('payment_methods', '0002_auto_20240610_0443'),
        ('orders', '0002_auto_20240120_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodorder',
            options={'verbose_name': 'Блюдо в Заказе', 'verbose_name_plural': 'Блюда в Заказе'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_info',
            field=models.TextField(blank=True, null=True, verbose_name='дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(through='orders.FoodOrder', to='foods.Food', verbose_name='Блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_methods.paymentmethod', verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statuses.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Пользователь'),
        ),
    ]
