# Generated by Django 5.0.6 on 2024-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20240610_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/', verbose_name='Изображение'),
        ),
    ]
