# Generated by Django 3.2.9 on 2024-01-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('users', '0004_alter_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale'),
        ),
    ]
